[package]
name = "descent_macro_test"
version = "0.1.0"
authors = ["Paul Scott <paul.m.sco@gmail.com>"]
edition = "2018"

[dependencies]
descent = { path = "../../" }
descent_macro = { path = "../" }
