[package]
name = "descent_tests"
version = "0.1.0"
authors = ["Paul Scott <paul.m.sco@gmail.com>"]
edition = "2018"

[dev-dependencies]
descent = { path = "../descent" }
descent_macro = { path = "../descent_macro" }
